config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/index'
  resources :usuarios do
    resources :reclamacaos
  end
  root 'sessions#index'
  get 'index' => 'sessions#index'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reclamacao.rb
class Reclamacao < ApplicationRecord
  validates :titulo, presence: true, length: {maximum: 40}
  validates :texto, presence: true, length: {minimum: 10}
  validates :categoria, presence:true
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  has_many :reclamacaos, dependent: :destroy
  validates :login, presence: true, length: {minimum: 4},  uniqueness: {case_sensitive: true}
  validates :password_digest, presence: true, length: {minimum: 8}
  validates :nome, presence: true, length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
    unless logged_in?
      redirect_to root_url
    end
  end

  def correct_user?
    @usuario = Usuario.find(params[:id])
    unless current_user == @usuario
      redirect_to usuario_path
    end
  end


end

app/controllers/reclamacaos_controller.rb
class ReclamacaosController < ApplicationController
  before_action :get_usuario
  before_action :set_reclamacao, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show]

  # GET /reclamacaos
  # GET /reclamacaos.json
  def index
    @reclamacaos = @usuario.reclamacaos
  end

  # GET /reclamacaos/1
  # GET /reclamacaos/1.json
  def show
  end

  # GET /reclamacaos/new
  def new
    @reclamacao = @usuario.reclamacaos.build
  end

  # GET /reclamacaos/1/edit
  def edit
  end

  # POST /reclamacaos
  # POST /reclamacaos.json
  def create
    @reclamacao = @usuario.reclamacaos.build(reclamacao_params)

    respond_to do |format|
      if @reclamacao.save
        format.html { redirect_to usuario_reclamacaos_path(@usuario), notice: 'Reclamacao was successfully created.' }
        format.json { render :show, status: :created, location: @reclamacao }
      else
        format.html { render :new }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamacaos/1
  # PATCH/PUT /reclamacaos/1.json
  def update
    respond_to do |format|
      if @reclamacao.update(reclamacao_params)
        format.html { redirect_to usuario_reclamacaos_path(@usuario), notice: 'Reclamacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @reclamacao }
      else
        format.html { render :edit }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamacaos/1
  # DELETE /reclamacaos/1.json
  def destroy
    @reclamacao.destroy
    respond_to do |format|
      format.html { redirect_to usuario_reclamacaos_path(@usuario), notice: 'Reclamacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamacao
      @reclamacao = @usuario.reclamacaos.find(params[:id])
    end

    def get_usuario
      @usuario = Usuario.find(params[:usuario_id])
    end

    # Only allow a list of trusted parameters through.
    def reclamacao_params
      params.require(:reclamacao).permit(:titulo, :texto, :categoria, :empresa)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    i = 0
    @reclamacoes = []
    @usuarios = Usuario.all
    @usuarios.each do |user|
      user.reclamacaos.each do |reclam|
        @reclamacoes[i] = reclam
        i+=1
      end
    end
    return @reclamacoes
    Session.search(params[:search])
  end

  def self.search(search)
    if search!=nil
      puts search
    end
  end

  def new
  end

  def create
    @usuario = Usuario.find_by(login: params[:session][:login])
    if @usuario && @usuario.authenticate(params[:session][:password])
      sign_in
      redirect_to @usuario
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  private
  # Only allow a list of trusted parameters through.
  def session_params
    params.require(:usuario).permit(:search, :empresa)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]
  before_action :correct_user?, only: [:edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to sessions_new_path, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
    sign_out
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :login, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reclamacaos_helper.rb
module ReclamacaosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:usuario_id] = @usuario.id
  end

  def current_user
    @current_user ||= Usuario.find_by(id: session[:usuario_id])
  end

  def block_access
    if current_user.present?
      redirect_to usuario_path(@current_user)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:usuario_id)
    @current_user = nil
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <li><h3><%= current_user.nome %> </h3></li>
          <li>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings",
                              edit_usuario_path(current_user) %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", sessions_new_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReclameAqui</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/reclamacaos/_form.html.erb
<%= form_with(model: [@usuario, reclamacao], local: true) do |form| %>
  <% if reclamacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reclamacao.errors.count, "error") %> prohibited this reclamacao from being saved:</h2>

      <ul>
        <% reclamacao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Cadastrar Reclamação</h1>
    <div class="field">
      <%= form.label :titulo %>
      <%= form.text_field :titulo %>
    </div>

    <div class="field">
      <%= form.label :texto %>
      <%= form.text_area :texto %>
    </div>

    <div class="field">
      <%= form.label :categoria %>
      <%= form.text_field :categoria %>
    </div>

    <div class="field">
      <%=form.label :empresa%>
      <%= form.select :empresa, [['Empresa1', 'empresa1'], ['Empresa2', 'empresa2'], ['Empresa3', 'empresa3']], id:"empresa" %>

    </div>

  <div class="actions">
    <%= form.submit "Cadastrar", id:"submit" %>
  </div>

<%end %>

app/views/reclamacaos/edit.html.erb
<h1>Editing Reclamacao</h1>

<%= render 'form', reclamacao: @reclamacao %>

<%= link_to 'Show', [@usuario, @reclamacao] %> |
<%= link_to 'Back', usuario_reclamacaos_path(@usuario) %>

app/views/reclamacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reclamações</h1>
<% if !@usuario.reclamacaos.empty? %>
<table border="1">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Texto</th>
      <th>Ações</th></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamacaos.each do |reclamacao| %>
      <tr>
        <td><%= reclamacao.titulo %></td>
        <td><%= reclamacao.texto %></td>
        <td><%= link_to 'Visualizar', usuario_reclamacao_path(@usuario, reclamacao) %>
        <%= link_to 'Editar', edit_usuario_reclamacao_path(@usuario, reclamacao) %>
        <%= link_to 'Destruir', [@usuario, reclamacao], id:"d-#{reclamacao.titulo}", method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Voltar', [@usuario] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end %>

<br>

<%= link_to 'Nova Reclamação', new_usuario_reclamacao_path(@usuario) %>

app/views/reclamacaos/new.html.erb
<%= render 'form', reclamacao: @reclamacao %>

<%= link_to 'Back', usuario_reclamacaos_path(@usuario) %>

app/views/reclamacaos/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Reclamação</h1>
<p>
  <strong>Titulo:</strong>
  <%= @reclamacao.titulo %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @reclamacao.texto %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @reclamacao.categoria %>
</p>
<p>
  <strong>Empresa:</strong>
  <%= @reclamacao.empresa %>
</p>

<% if current_user != nil %>
  <%= link_to 'Editar', edit_usuario_reclamacao_path(@usuario, @reclamacao) %> |
<% end %>
<%= link_to 'Voltar', usuario_reclamacaos_path(@usuario) %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id:"login" %>
  </div>

  <div class="field">
    <%= form.label :Senha %>
    <%= form.password_field :password, id:"senha" %>
  </div>
  <div class="field">
    <%= form.label :Confirmar_Senha %>
    <%= form.password_field :password_confirmation, id:"confirmar_senha" %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id:"nome" %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar", id:"submit" %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Voltar', usuario_path(current_user) %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Login</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.login %></td>
        <td><%= link_to 'Exibir Usuário', usuario %></td>
        <td><%= link_to 'Editar Usuário', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destruir Usuário', usuario, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<html>
<body>
<% if current_user == @usuario %>
  <ul>
    <%= link_to 'Reclamações', usuario_reclamacaos_path(current_user) %> |
    <%= link_to "Deletar Usuário", @usuario, method: :delete %> |
    <%= link_to 'Voltar', sessions_index_path %>
  </ul>
<% end %>
<br>
</body>
</html>
<h2>Reclamações</h2>
<% if !@usuario.reclamacaos.empty? %>
  <table border="1">
    <tr>
      <th>Titulo</th>
      <th>Texto</th>
    </tr>
    <% @usuario.reclamacaos.each do |rec| %>
      <tr>
        <td>
          <%= rec.titulo %>
        </td>
        <td>
          <%= rec.texto %>
        </td>
      </tr>
    <% end %>

  </table>
<% end %>